// Code generated by mockery v2.13.1. DO NOT EDIT.

package cli

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockEngine is an autogenerated mock type for the Engine type
type MockEngine struct {
	mock.Mock
}

// Run provides a mock function with given fields: args, stdin, stdout
func (_m *MockEngine) Run(args []string, stdin io.Reader, stdout io.Writer) int {
	ret := _m.Called(args, stdin, stdout)

	var r0 int
	if rf, ok := ret.Get(0).(func([]string, io.Reader, io.Writer) int); ok {
		r0 = rf(args, stdin, stdout)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

type mockConstructorTestingTNewMockEngine interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockEngine creates a new instance of MockEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockEngine(t mockConstructorTestingTNewMockEngine) *MockEngine {
	mock := &MockEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
